### ISSUE TITLE
Garden Tools magnet crash

### ISSUE THREAD

**Issue by mason3ck** [JonasBonno/docker-ftb-endeavour#3]
Attempting to use the Garden Tools mod's magnet crashes the game and disallows access.
I had placed the magnet a top a livestock rancher block and immediately the server crashed.
It will not relaunch due to the block existing

[crash-2021-07-09_13.26.21-server.txt](https://github.com/JonasBonno/docker-ftb-endeavour/files/6793398/crash-2021-07-09_13.26.21-server.txt)

**Comment by JonasBonno** [comment]
Hi,
I am not the creator of the Minecraft modpack, I am just provide a convenient docker container you can use.
I suggest you report the bug on the FTB forum: https://forum.feed-the-beast.com/

In the meantime you may be able to get the server working again by restoring the world to the data container from one af the zip-files in the "/minecraft/backups" from before to placed the magnet.

Let me know if this helps you.
